environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: stable
  - TARGET: i686-pc-windows-msvc
    CHANNEL: stable
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: nightly-2019-08-16
  - TARGET: i686-pc-windows-msvc
    CHANNEL: nightly-2019-08-16

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc --version
  - rustup --version
  - cargo --version

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose

branches:
  only:
    - staging # bors r+
    - trying  # bors try
    - master
